services:
  backend:
    build: ./backend
    security_opt:
      - no-new-privileges:true
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
    depends_on:
      - backend
